app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sheet/", include("sheet.urls", namespace="sheet")),
    path("manymailbox/", include("manymailbox.urls", namespace="manmailbox")),
]

app/sheet/urls.py
from django.urls import path
from .views import (
    add_sales_manager,
    all_traders,
    create_qr_code,
    delete_sales_manager,
    edit_sales_manager,
    specific_trader,
    find_trader,
    find_trader_dok,
    upload_sales_branch_view,
    upload_sales_manager_view,
)

app_name = "sheet"

urlpatterns = [
    path("csv/", upload_sales_manager_view, name="upload_view"),
    path("csv-branches/", upload_sales_branch_view, name="upload_sales_branch_view"),
    path("all-traders/", all_traders, name="all_traders"),
    path("submit/", find_trader, name="submit"),
    path("submit/<int:pk>/", specific_trader, name="specific_trader"),
    path("submit-dok/", find_trader_dok, name="submit_dok"),
    path("add-sales-manager/", add_sales_manager, name="add_sales_manager"),
    path(
        "add-sales-manager/<int:id_number>/",
        edit_sales_manager,
        name="edit_sales_manager",
    ),
    path(
        "delete-sales-manager/<int:id_number>/",
        delete_sales_manager,
        name="delete_sales_manager",
    ),
    path("create-qrcode/", create_qr_code, name="create_qr_code"),
]

app/sheet/models.py
from django.db import models
import uuid


class Csv(models.Model):
    file_name = models.FileField(upload_to="csvs")
    upload = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.file_name}: {self.upload}"


class SalesBranch(models.Model):
    short_name = models.CharField(max_length=3)
    full_name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.short_name}"

    @classmethod
    def get_full_name(cls, short_name, full_name):
        return cls(short_name, "-", full_name)


class SalesManager(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=64)
    sales_branch = models.ForeignKey(
        SalesBranch, verbose_name="Oddzial", on_delete=models.DO_NOTHING
    )
    area = models.CharField(max_length=128)
    position = models.CharField(max_length=128)
    supervisor = models.CharField(null=True, blank=True, max_length=128)
    phone_number = models.CharField(max_length=18)
    email = models.EmailField()
    id_number = models.PositiveIntegerField()
    is_active = models.BooleanField(default=True)
    photo = models.ImageField(upload_to="images", null=True, blank=True)
    qr_code = models.ImageField(upload_to="qr_codes", null=True, blank=True)

    def __str__(self):
        return str(self.id_number)

    @classmethod
    def get_sales_manager_id(self):
        return (self.sales_branch)(self.id_number)

app/sheet/forms.py
from django.forms import ModelForm

from .models import Csv, SalesManager


class CsvModelForm(ModelForm):
    class Meta:
        model = Csv
        fields = ("file_name",)


class SalesManagerForm(ModelForm):
    class Meta:
        model = SalesManager
        fields = [
            "first_name",
            "last_name",
            "sales_branch",
            "area",
            "position",
            "supervisor",
            "phone_number",
            "email",
            "is_active",
            "photo",
            "qr_code",
        ]
        labels = {
            "first_name": "Imię",
            "last_name": "Nazwisko",
            "sales_branch": "Oddział",
            "area": "Rejon",
            "position": "Stanowisko",
            "supervisor": "Numer przełożonego",
            "phone_number": "Numer pracownika",
            "email": "Email pracownika",
            "is_active": "Czy aktywny",
            "photo": "Zdjęcie",
            "qr_code": "Kod QR"
        }

app/sheet/views.py
import re
import csv
import qrcode

from django.shortcuts import get_object_or_404, redirect, render

from .core import unique_sales_manager_id
from .models import SalesBranch, Csv, SalesManager
from .forms import CsvModelForm, SalesManagerForm


def upload_sales_manager_view(request):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, "r") as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    row = "".join(row)
                    row = row.split(";")
                    sales_branch_raw = str(row[2])
                    var1 = unique_sales_manager_id()
                    sales_branch = SalesBranch.objects.get(short_name=sales_branch_raw)
                    SalesManager.objects.create(
                        first_name=str(row[0]),
                        last_name=str(row[1]),
                        sales_branch=sales_branch,
                        area=str(row[3]),
                        position=str(row[4]),
                        supervisor=str(row[5]),
                        phone_number=int(row[6]),
                        email=str(row[7]),
                        id_number=var1,
                        is_active=True,
                    )
            obj.activated = True
            obj.save()
    return render(request, "upload.html", {"form": form})


def upload_sales_branch_view(request):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, "r") as f:
            reader = csv.reader(f)

            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    row = "".join(row)
                    row = row.split(";")
                    SalesBranch.objects.create(
                        short_name=str(row[0]),
                        full_name=str(row[1]),
                    )
            obj.activated = True
            obj.save()
    return render(request, "upload-branches.html", {"form": form})


def all_traders(request):
    traders = SalesManager.objects.all()
    return render(request, "all-selers.html", {"test": traders})


def specific_trader(request, pk):
    trader = SalesManager.objects.filter(id_number=pk)
    return render(request, "sales-manager.html", {"test": trader})


def specific_trader_last_name(request, pk):
    pk = f"{pk}"
    trader = SalesManager.objects.filter(last_name=f"{pk}")
    return render(request, "sales-manager.html", {"test": trader})


def find_trader(request):
    if request.method == "POST":
        pk = request.POST.get("fname")
        try:
            pk = re.search("\d+", pk)[0]
            try:
                pk = int(pk)
                return specific_trader(request, pk)
            except ValueError:
                return render(request, "submit.html")
        except TypeError:
            return render(request, "submit.html")
    return render(request, "submit.html")


def find_trader_dok(request):
    if request.method == "POST":

        pk_number = request.POST.get("fname")
        if pk_number is not None:
            try:
                pk = int(pk_number)
                find_id_in_base = SalesManager.objects.filter(id_number=pk)
                if len(find_id_in_base) == 0:
                    find_object = SalesManager.objects.filter(phone_number=pk)
                    try:
                        pk = find_object[0]
                        pk = pk.id_number
                    except:
                        pass
                return specific_trader(request, pk)

            except ValueError:
                data = str(pk_number.capitalize())
                try:
                    find_object = SalesManager.objects.filter(last_name=data)
                    pk = find_object[0]
                    pk = pk.id_number
                    return specific_trader(request, pk)
                except IndexError:
                    return render(request, "submit-dok.html")

    return render(request, "submit-dok.html")


def add_sales_manager(request):
    id_number = unique_sales_manager_id()
    if request.method == "POST":
        form = SalesManagerForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.id_number = id_number
            post.save()
            return redirect("/sheet/all-traders/")
    else:
        form = SalesManagerForm()

    return render(request, "add-sales-manager.html", {"form": form})


def edit_sales_manager(request, id_number):
    instance = get_object_or_404(SalesManager, id_number=id_number)
    form = SalesManagerForm(data=request.POST or None, instance=instance)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            traders = SalesManager.objects.all()
            return redirect("/sheet/all-traders/")

    return render(request, "add-sales-manager.html", {"form": form})


def delete_sales_manager(request, id_number):
    instance = get_object_or_404(SalesManager, id_number=id_number)
    form = SalesManagerForm(data=request.POST or None, instance=instance)

    if request.method == "POST":
        instance.delete()
        return redirect("/sheet/all-traders/")

    return render(request, "delete-sales-manager.html", {"form": form})


def create_qr_code(request):
    all_selers = SalesManager.objects.all()
    for seler in all_selers:
        var = str(seler.id_number)
        # img = qrcode.make("http://127.0.0.1:8000/sheet/submit/781450/")
        # img.save("781450.jpg"),
        # img = qrcode.make("https://gmp.solidsecurity.pl/handlowy/submit/564526/")
        # img.save("564526.jpg")
        adress = "https://gmp.solidsecurity.pl/handlowy/submit/"+var+"/"
        img = qrcode.make(adress)
        patch = "C:\\Users\\dobry\\VSCode\\portfolio\\app\\sheet\\qr_code\\"+var+".jpg"
        img.save(patch)
        update_seler = SalesManager.objects.filter(id=seler.id).update(qr_code=patch)
        
    
    return render(request, "all-selers.html", {"test": all_selers})

app/sheet/templates/add-sales-manager.html
{% load i18n %}

{% block title %}
Dodaj Handlowca
{% endblock %}

{% get_current_language as LANGUAGE_CODE %}

{% block content %}

<section>
    <div class="row">
        <div class="col-md-6">
            <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Dane Handlowca</h4> 
            <div class="card-body">
                <div class="table-responsive">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table border="0">
                            <tr>
                                <th>{{ form.first_name.label_tag }}</th>
                                <td>{{ form.first_name }}</td>
                                <td>{{ form.first_name.errors }}</td>
                            </tr>
                            <tr>
                                <th>{{ form.last_name.label_tag }}</th>
                                <td>{{ form.last_name }}</td>
                                <td>{{ form.last_name.errors }}</td>
                            </tr>
                            <tr>
                                <th>{{ form.sales_branch.label_tag }}</th>
                                <td>{{ form.sales_branch }}</td>
                                <td>{{ form.sales_branch.errors }}</td>                                    
                            </tr>
                            <tr>
                                <th>{{ form.area.label_tag }}</th>
                                <td>{{ form.area }}</td>
                                <td>{{ form.area.errors }}</td>
                            </tr>
                            <tr>
                                <th>{{ form.position.label_tag }}</th>
                                <td>{{ form.position }}</td>
                                <td>{{ form.position.errors }}</td>
                            </tr>
                            <tr>
                                <th>{{ form.supervisor.label_tag }}</th>
                                <td>{{ form.supervisor }}</td>
                                <td>{{ form.supervisor.errors }}</td>
                            </tr>   
                            <tr>
                                <th>{{ form.phone_number.label_tag }}</th>
                                <td>{{ form.phone_number }}</td>
                                <td>{{ form.phone_number.errors }}</td>
                            </tr>    
                            <tr>
                                <th>{{ form.email.label_tag }}</th>
                                <td>{{ form.email }}</td>
                                <td>{{ form.email.errors }}</td>
                            </tr>  
                            <tr>
                                <th>{{ form.is_active.label_tag }}</th>
                                <td>{{ form.is_active }}</td>
                            </tr>    
                        </table>
                        <button class="btn btn-primary" type="submit">Zapisz dane</button>
                    </form> 
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/sheet/templates/all-selers.html
{% load i18n %}

{% block title %}
Handlowcy
{% endblock %}


{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<section>
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Dane Handlowców</h4>
    </div>         
</section>

<section>
    <button class="btn btn-primary" onclick="location.href='{% url 'sheet:submit' %}'">
        Powrót do wyszukiwania
    </button>
    <button class="btn btn-primary" onclick="location.href='{% url 'sheet:upload_view' %}'">
        Wczytaj plik z handlowcami
    </button>
    <button class="btn btn-primary" onclick="location.href='{% url 'sheet:upload_sales_branch_view' %}'">
        Wczytaj plik z oddziałami
    </button>
    </br>    
</section>
</br>
<section>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="dataTableExample" class="table table-centered td-center">
                            <thead>
                                <tr>
                                    <th scope="col">Imię</th>
                                    <th scope="col">Nazwisko</th>
                                    <th scope="col">Oddział</th>
                                    <th scope="col">Rejon</th>
                                    <th scope="col">Stanowisko</th>
                                    <th scope="col">Przełożony</th>
                                    <th scope="col">Telefon</th>
                                    <th scope="col">Adres Email</th>
                                    <th scope="col">Identyfikator</th>
                                    <th scope="col">Edycja</th>
                                    <th scope="col">Usuwanie</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in test %}
                                <tr>
                                    <td>{{ item.first_name }}</td>
                                    <td> {{ item.last_name }}</td>
                                    <td> {{ item.sales_branch }}</td>
                                    <td> {{ item.area }}</td> 
                                    <td> {{ item.position }}</td>
                                    <td> {{ item.supervisor }}</td>
                                    <td> {{ item.phone_number }}</td>
                                    <td> {{ item.email }}</td>
                                    <td> {{ item.sales_branch.short_name }}-{{ item.id_number }}</td>
                                    <td>
                                        <form action="/sheet/add-sales-manager/{{ item.id_number }}/">
                                            <input class="btn btn-primary" type="submit" value="Edytuj">
                                        </form></td>
                                    <td>
                                        <form action="/sheet/delete-sales-manager/{{ item.id_number }}/">
                                            <input class="btn btn-primary" type="submit" value="Usuń">
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>       
                        </table>
                    </div>
                </div>
            </div>
        </div>
     </div>
</section>

{% endblock %}

app/sheet/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
   
      <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>uploads - {% block title %}{% endblock title %}</title>
    <style>
      a{color: white;}
      a:link {text-decoration: none}
      a:visited {text-decoration: none}
      a:active {text-decoration: none}
      a:hover { color: white }{text-decoration: underline}
    </style>
  </head>
  <body>
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

  </body>
</html>

app/sheet/templates/delete-sales-manager.html
{% load i18n %}

{% block title %}
Usuń Handlowca
{% endblock %}

{% get_current_language as LANGUAGE_CODE %}

{% block content %}


<section>
    <div class="row">
        <div class="col-md-6">
            <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Dane Handlowca</h4> 
            </br>
            <h5 class="mb-3 mb-md-0">
                UWAGA operacja jest nieodwracalna.
            </br>
            </br>CZY CHCESZ KONTYNUOWAĆ?</h5>
                <div class="card-body">
                    <div class="table-responsive">
                        <form method="post" novalidate>
                            {% csrf_token %}
                            <button class="btn btn-primary" type="submit">Usuń Konto</button>
                        </form> 
                    </div>
                </div>
        </div>
    </div>
</section>

{% endblock %}

app/sheet/templates/sales-manager.html
{% load static %}
{% load i18n %}


{% block title %}
Handlowiec
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
{% endblock %}


{% block content %}
{% get_current_language as LANGUAGE_CODE %}


<title>{% block Pracownicy %}{% endblock %}</title>

<section>
    {% if test|length == 0 %}
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="user"></i>BRAK TAKIEGO NUMERU W BAZIE</h4> 
        </div>   
    </div>      
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn btn-primary" onclick="location.href='{% url 'sheet:submit' %}'">
                Powrót do Wyszukiwania
            </button>
        </form>
    </div>

    {% else %}
   
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <div class="table-responsive">
                    <table id="dataTableExample" class="table table-centered td-center">
                    {% for item in test %}
                        <thead>
                            <tr>
                                <th scope="col"><h3 class="mb-3 mb-md-0">DANE PRACOWNIKA</h3></th>
                            </tr>    
                            <tr>
                                <th scope="col">Imię</th>
                                <td>{{ item.first_name }}</td>
                            </tr>
                            <tr>
                                <th scope="col">Nazwisko</th>
                                <td> {{ item.last_name }}</td>
                            </tr>
                            <tr>
                                <th scope="col">Oddział</th>
                                <td> {{ item.sales_branch.full_name }}</td>
                            </tr>
                            <tr>
                                <th scope="col">Rejon</th>
                                <td> {{ item.area }}</td> 
                            </tr>
                            <tr>
                                <th scope="col">Stanowisko</th>
                                <td> {{ item.position }}</td> 
                            </tr>
                            <tr>
                                <th scope="col">Telefon do Przełożonego</th>
                                <td> {{ item.supervisor }}</td> 
                            </tr>
                            <tr>
                                <th scope="col">Telefon</th>
                                <td> {{ item.phone_number }}</td> 
                            </tr>
                            <tr>
                                <th scope="col">Adres Email</th>
                                <td> {{ item.email }}</td> 
                            </tr>
                            <tr>
                                <th scope="col">Identyfikator</th>
                                <td> {{item.sales_branch }}-{{ item.id_number }}</td> 
                            </tr>
                        </thead>
                    {% endfor %}
                    </table>
                    </br>
                    <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        <button class="btn btn-primary" onclick="location.href='{% url 'sheet:submit' %}'">
                            Powrót do Wyszukiwania
                        </button>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endblock content %}

app/sheet/templates/submit-dok.html
{% load static %}
{% load i18n %}


{% block title %}
    Znajdź Handlowca
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
{% endblock %}

<body>
{% block content %}
<section>
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Znajdź Handlowca</h4>
    </div>         
</section>

<section> 
    <table border="0">
        <tr>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <th>Wyszukaj pracownika w bazie:</th>
                <td><input align="center"type="text" id="fname" name="fname"{{pk}} ></td>
                <td><button class="btn btn-primary" type="submit">Znajdż osobę</button></td>
            </form>
        </tr>
        <tr>
            <th>Możesz to zrobić za pomocą:</th>
        </tr> 
        <tr>
            <th>&bull; Nazwiska</th>
        </tr>
        <tr>
            <th>&bull; Numeru Telefonu</th>
        </tr>
        <tr>
            <th>&bull; ID bez prefiksu</th>
        </tr>
    </table>
    </br>
    <th>
        <button class="btn btn-primary" onclick="location.href='{% url 'sheet:all_traders' %}'">
            Powrót do listy
        </button>
    </th>
        

</section>


{% endblock %}
</body>

app/sheet/templates/submit.html
{% comment %} {% extends "global/base.html" %} {% endcomment %}
{% load static %}
{% load i18n %}


{% block title %}
Znajdź Pracownika
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
{% endblock %}

{% get_current_language as LANGUAGE_CODE %}

<body>
{% block content %}

<section>
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="user"></i>WPISZ NUMER NASZEGO PRACOWNIKA</h4> 
        </div>   
    </div>      
</section>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    </br>
    <input align="center"type="text" id="fname" name="fname"{{pk}} >
    </br>
    </br>
    <button class="btn btn-primary" type="submit">Sprawdź</button>
</form> 

{% endblock %}
</body>

app/sheet/templates/upload-branches.html
{% extends 'base.html' %}

{% block title %}
    Dodaj Oddziały
{% endblock title%}

{% block content %}
<form action="" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}}
    {{form}}
    <button type="submit" class="ui button primary">Potwierdź</button>
</form>
</br>
    <button type="submit" class="ui button primary">
        <a href="{% url 'sheet:all_traders' %}" id="myButton">Spis Handlowców</a>
    </button>
{% endblock content %}

app/sheet/templates/upload.html
{% extends 'base.html' %}

{% block title %}
    Importowanie Handlowców
{% endblock title%}

{% block content %}
<form action="" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}}
    {{form}}
    <button type="submit" class="ui button primary">Potwierdź</button>
</form>
</br>
<button type="submit" class="ui button primary">
    <a href="{% url 'sheet:all_traders' %}" id="myButton">Spis Handlowców</a>
</button>
{% endblock content %}