app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sheet/", include("sheet.urls", namespace="sheet")),
    path("manymailbox/", include("manymailbox.urls", namespace="manmailbox")),
]

app/manymailbox/urls.py
from django.urls import path
from .views import (
    add_mailbox,
    all_mailboxes,
    delete_mailbox,
    edit_mailbox,
    all_emails,
    login_errors,
    send_emails,
    check_mailboxes,
)

app_name = "manymailbox"

urlpatterns = [
    path("check-emails/", check_mailboxes, name="check_emails"),
    path("all-emails/", all_emails, name="all_emails"),
    path("send-emails/", send_emails, name="send_emails"),
    path("all-mailboxes/", all_mailboxes, name="all_mailboxes"),
    path("add-mailbox/", add_mailbox, name="add_mailbox"),
    path("add-mailbox/<int:id>/", edit_mailbox, name="edit_mailbox"),
    path("delete-mailbox/<int:id>/", delete_mailbox, name="delete_mailbox"),
    path("errors/", login_errors, name="login_errors"),
]

app/sheet/urls.py
from django.urls import path
from .views import (
    add_sales_manager,
    all_traders,
    create_qr_code,
    delete_sales_manager,
    edit_sales_manager,
    specific_trader,
    find_trader,
    find_trader_dok,
    upload_sales_branch_view,
    upload_sales_manager_view,
)

app_name = "sheet"

urlpatterns = [
    path("csv/", upload_sales_manager_view, name="upload_view"),
    path("csv-branches/", upload_sales_branch_view, name="upload_sales_branch_view"),
    path("all-traders/", all_traders, name="all_traders"),
    path("submit/", find_trader, name="submit"),
    path("submit/<int:pk>/", specific_trader, name="specific_trader"),
    path("submit-dok/", find_trader_dok, name="submit_dok"),
    path("add-sales-manager/", add_sales_manager, name="add_sales_manager"),
    path(
        "add-sales-manager/<int:id_number>/",
        edit_sales_manager,
        name="edit_sales_manager",
    ),
    path(
        "delete-sales-manager/<int:id_number>/",
        delete_sales_manager,
        name="delete_sales_manager",
    ),
    path("create-qrcode/", create_qr_code, name="create_qr_code"),
]

app/manymailbox/models.py
from django.db import models


class Mailbox(models.Model):
    name = models.CharField(max_length=32)
    server = models.CharField(max_length=128)
    port = models.CharField(max_length=6, null=True, blank=True)
    email_user = models.CharField(max_length=128)
    email_password = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.name}"


class DestinationInbox(models.Model):
    email = models.CharField(max_length=128)
    company = models.CharField(max_length=64, null=True, blank=True)
    mailbox = models.ManyToManyField(Mailbox, blank=True)

    def __str__(self):
        return f"{self.email}"


class RecievedMail(models.Model):
    email_uidl = models.CharField(max_length=128)
    send_date = models.DateTimeField(blank=True, null=True)
    email_sender = models.CharField(max_length=128)
    email_receiver = models.CharField(blank=True, null=True, max_length=128)
    subject = models.CharField(max_length=128)
    email_body = models.TextField(max_length=10000, null=True, blank=True)
    is_forwarded = models.BooleanField(default=False)
    send_to = models.CharField(max_length=256, blank=True, null=True)
    save_to_db_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.subject}"

app/manymailbox/forms.py
from django.forms import ModelForm

from .models import Mailbox


class MailboxForm(ModelForm):
    class Meta:
        model = Mailbox
        fields = [
            "name",
            "server",
            "port",
            "email_user",
            "email_password",
        ]
        labels = {
            "name": "Nazwa Skrzynki",
            "server": "Serwer pocztowy",
            "port": "Port",
            "email_user": "Adres email",
            "email_password": "hasło do skrzynki",
        }

app/manymailbox/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail

from .forms import MailboxForm
from .models import DestinationInbox, Mailbox, RecievedMail
from .email_reader import connect_pop_server, connect_imap_server


def add_mailbox(request):
    if request.method == "POST":
        form = MailboxForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect("/manymailbox/all-emails/")
    else:
        form = MailboxForm()

    return render(request, "add-mailbox.html", {"form": form})


def all_mailboxes(request):
    mailbox = Mailbox.objects.all()
    return render(request, "all-mailboxes.html", {"test": mailbox})


def edit_mailbox(request, id):
    instance = get_object_or_404(Mailbox, id=id)
    form = MailboxForm(data=request.POST or None, instance=instance)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("/manymailbox/all-mailboxes/")

    return render(request, "add-mailbox.html", {"form": form})


def delete_mailbox(request, id):
    instance = get_object_or_404(Mailbox, id=id)
    form = MailboxForm(data=request.POST or None, instance=instance)

    if request.method == "POST":
        instance.delete()
        return redirect("/manymailbox/all-mailboxes/")

    return render(request, "delete-mailbox.html", {"form": form})


def all_emails(request):
    emails = RecievedMail.objects.all().order_by("send_date")
    return render(request, "all-emails.html", {"test": emails})


def login_errors(request, user):
    obj = Mailbox.objects.get(email_user=user)
    id = obj.id
    return render(request, "errors.html", {"user": user, "id": id})


def check_mailboxes(request):
    mailbox_counter = -1
    mailboxes = Mailbox.objects.all()
    for mailbox in mailboxes:
        port = mailbox.port
        user = mailbox.email_user
        if port == "993":  # imap server
            mailbox_counter += 1
            check_errors = connect_imap_server(mailbox, mailbox_counter)
            if check_errors == True:
                return login_errors(request, user)
        elif port == "995":  # pop server
            mailbox_counter += 1
            check_errors = connect_pop_server(mailbox, mailbox_counter)
            if check_errors == True:
                return login_errors(request, user)
        else:  # incorrect port
            mailbox_counter += 1
            return login_errors(request, user)

    return render(request, "check-emails.html", {"user": user})


def send_emails(request):
    new_emails = RecievedMail.objects.filter(is_forwarded=False)
    query_set_len = len(new_emails)
    email_counter = -1
    for _ in range(query_set_len):  # number of emails-object
        email_counter += 1
        new_email = new_emails[email_counter]
        parsed_email_reciever = new_email.email_receiver
        specific_mailbox = DestinationInbox.objects.filter(
            mailbox__email_user=parsed_email_reciever
        )
        mail_to_sent_list = []
        for mail in specific_mailbox:
            mail_to_sent_list.append(mail.email)

        send_mail(
            new_email.subject,
            new_email.email_body,
            new_email.email_sender,
            mail_to_sent_list,
            fail_silently=False,
        )
        update_email_object = RecievedMail.objects.get(id=new_email.id)
        update_email_object.is_forwarded = True
        update_email_object.send_to = mail_to_sent_list
        update_email_object.save()

    return render(request, "send-emails.html")

app/manymailbox/templates/add-mailbox.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
Dodaj skrzynkę
{% endblock %}

{% block content %}

<section>
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card" style="border-color: #e99245;background-color: #f7eee8;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Wiadomości Email</h4>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table id="dataTableExample" class="table table-centered td-center">
                                <tr>
                                    <th>{{ form.name.label_tag }}</th>
                                    <td>{{ form.name }}</td>
                                    <td>{{ form.name.errors }}</td>
                                </tr>
                                <tr>
                                    <th>{{ form.server.label_tag }}</th>
                                    <td>{{ form.server }}</td>
                                    <td>{{ form.server.errors }}</td>
                                </tr>
                                <tr>
                                    <th>{{ form.port.label_tag }}</th>
                                    <td>{{ form.port }}</td>
                                    <td>{{ form.port.errors }}</td>                                    
                                </tr>
                                <tr>
                                    <th>{{ form.area.label_tag }}</th>
                                    <td>{{ form.area }}</td>
                                    <td>{{ form.area.errors }}</td>
                                </tr>
                                <tr>
                                    <th>{{ form.email_user.label_tag }}</th>
                                    <td>{{ form.email_user }}</td>
                                    <td>{{ form.email_user.errors }}</td>
                                </tr>
                                <tr>
                                    <th>{{ form.email_password.label_tag }}</th>
                                    <td>{{ form.email_password }}</td>
                                    <td>{{ form.email_password.errors }}</td>
                                </tr>         
                            </table>
                            <button class="btn btn-primary" style="background-color: #e99245;" type="submit">Zapisz dane</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

app/manymailbox/templates/all-emails.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
Emaile
{% endblock %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
    $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
    });
    });
</script>

<body>
    <section>
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card" style="border-color: #e99245;background-color: #f7eee8;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-4">
                                <input style="border-color: #e99245;" id="myInput" type="text" placeholder="Search..">
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Wiadomości Email</h4>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="dataTableExample" class="table table-centered td-center">
                                <thead>
                                    <tr>
                                        <th scope="col">Data wysłania</th>
                                        <th scope="col">Nadawca</th>
                                        <th scope="col">Odbiorca</th>
                                        <th scope="col">Temat</th>
                                        <th scope="col">Treść</th>
                                    </tr>
                                </thead>
                                <tbody id="myTable">
                                    {% for item in test %}
                                    <tr>
                                        <td> {{ item.send_date }}</td>
                                        <td> {{ item.email_sender }}</td>
                                        <td> {{ item.email_receiver }}</td>
                                        <td> {{ item.subject|truncatewords:4 }}</td> 
                                        <td> {{ item.email_body|truncatewords:6 }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>       
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
{% endblock content %}

app/manymailbox/templates/all-mailboxes.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
Skrzynki Pocztowe
{% endblock %}


{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
    $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
    });
    });
</script>

<body>
    <section>
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card" style="border-color: #e99245;background-color: #f7eee8;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-4">
                                <input style="border-color: #e99245;" id="myInput" type="text" placeholder="Search..">
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i>Dane Skrzynek mailowych</h4>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="dataTableExample" class="table table-centered td-center">
                                <thead>
                                    <tr>
                                        <th scope="col">Nazwa</th>
                                        <th scope="col">Serwer</th>
                                        <th scope="col">Port</th>
                                        <th scope="col">Adres Email</th>
                                        <th scope="col">Hasło</th>
                                        <th scope="col">Edytuj</th>
                                        <th scope="col">Usuń</th>
                                    </tr>
                                </thead>
                                <tbody id="myTable">
                                    {% for item in test %}
                                    <tr>
                                        <td>{{ item.name }}</td>
                                        <td> {{ item.server }}</td>
                                        <td> {{ item.port }}</td>
                                        <td> {{ item.email_user }}</td> 
                                        <td> {{ item.email_password }}</td>
                                        <td>
                                            <form action="/manymailbox/add-mailbox/{{ item.id }}/">
                                                <input class="btn btn-primary" style="background-color: #e99245;" type="submit" value="Edytuj">
                                            </form></td>
                                        <td>
                                            <form action="/manymailbox/delete-mailbox/{{ item.id }}/">
                                                <input class="btn btn-primary" style="background-color: #e99245;" type="submit" value="Usuń">
                                            </form>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>       
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
{% endblock %}

app/manymailbox/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head> 

<body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #e99245;"  >
    <a class="navbar-brand" onclick="location.href='{% url 'manymailbox:all_emails' %}'"><h4>ManyMailBox</h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
</nav>
<nav class="sidebar">
    <div class="sidebar-header">
        <div class="sidebar-brand">
        </br>
        <button class="btn btn-primary" style="background-color: #e99245;width: 15%" onclick="location.href='{% url 'manymailbox:check_emails' %}'">
        Sprawdź skrzynki mailowe 
        </button>
        </div>  
    </div>   
    <div class="sidebar-header">
        <div class="sidebar-brand">
        </br>
        <button class="btn btn-primary" style="background-color: #e99245;width: 15%" onclick="location.href='{% url 'manymailbox:add_mailbox' %}'">
        Dodaj Skrzynkę mailową 
        </button>
        </div>  
    </div>    
    <div class="sidebar-header">
        <div class="sidebar-brand">
        </br>
        <button class="btn btn-primary" style="background-color: #e99245;width: 15%" onclick="location.href='{% url 'manymailbox:all_emails' %}'">
        Pokaż Wiadomości
        </button>
        </div>  
    </div> 
    <div class="sidebar-header">
        <div class="sidebar-brand">
        </br>
        <button class="btn btn-primary" style="background-color: #e99245;width: 15%" onclick="location.href='{% url 'manymailbox:all_mailboxes' %}'">
        Pokaż dodane skrzynki
        </button>
        </div>  
    </div>
</nav>

    

<div class="container">

    {% block content %}
    {% endblock %}

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

app/manymailbox/templates/check-emails.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}
Sprawdź Emaile
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
{% endblock %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}
<head>
    <script>
       setTimeout(function(){
            window.location.href = '/manymailbox/send-emails';
         }, 5);
    </script>
</head>
<body>
</body>
{% endblock content %}

app/manymailbox/templates/delete-mailbox.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
Usuń dane poczty email
{% endblock %}

{% get_current_language as LANGUAGE_CODE %}

{% block content %}


<section>
    <div class="row">
        <div class="col-md-6">
            <h4 class="mb-3 mb-md-0"><i class="link-icon" data-feather="users"></i> Usunięcie skrzynki</h4> 
            </br>
            <h5 class="mb-3 mb-md-0">
                UWAGA Jeśli nie masz zapisanych danych 
                </br>
                do konfiguracji skrzynki, stracisz je.
            </br>
            </br>CZY CHCESZ KONTYNUOWAĆ?</h5>
                <div class="card-body">
                    <div class="table-responsive">
                        <form method="post" novalidate>
                            {% csrf_token %}
                            <button class="btn btn-primary" style="background-color: #e99245;width: 40%" type="submit">Usuń skrzynkę</button>
                        </form> 
                    </div>
                </div>
        </div>
    </div>
</section>

{% endblock %}

app/manymailbox/templates/errors.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
Błąd Pobierania
{% endblock %}

{% block content %}
</br>
<h4>Nie udało nam się połączyć z 
</br>
nastepującą skrzynką pocztową.</h4>
</br>
<h5>{{ user }}</h5>
</br>
Jeśli jest to skrzynka Gmail, zaloguj się  
</br>
i w ustawieniach konta zaznacz: <h6 style="color:blue">"Włącz dostęp"</h6>
W pozycji: 
<h6 style="color:blue">"Dostęp mniej bezpiecznych aplikacji"</h6>



<section>
    <button class="btn btn-primary" style="background-color: #e99245;" onclick="location.href='https://myaccount.google.com/intro/security'">
        Ustawienia bezpieczeństwa Konta Google
    </button>
</section>
</br>
Jeżeli problem wystepuje nadal, spróbuj poprawić 
</br>
wprowadzone dane lub usuń te skrzynkę:
<p>

<section>
    <form action="/manymailbox/add-mailbox/{{ id }}/">
        <input class="btn btn-primary" style="background-color: #e99245;width: 25%" type="submit" value="Popraw dane">
    </form>
    </br>
    <form action="/manymailbox/delete-mailbox/{{ id }}/">
        <input class="btn btn-primary" style="background-color: #e99245;width: 25%" type="submit" value="Usuń skrzynkę">
    </form>
</section>

{% endblock %}

app/manymailbox/templates/send-emails.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}
Wyślij emaile
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
{% endblock %}


{% block content %}

{% get_current_language as LANGUAGE_CODE %}
    <script>
       setTimeout(function(){
            window.location.href = '/manymailbox/all-emails';
         }, 5);
   </script>
</head>
<body>
</body>

{% endblock content %}